// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Iq",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          <Toaster position="top-center" />

//         {children}
//       </body>
//     </html>
//   );
// }



"use client";

import './globals.css';

import { Inter } from 'next/font/google';

import Header from '@/components/header';
import HeaderMobile from '@/components/header-mobile';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import SideNav from '@/components/side-nav';
import Footer from '@/components/footer';
import { Toaster } from "react-hot-toast";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ['latin'] });



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isLoginPage = pathname === "/"; // Check if it's the login page

  return (
    <html lang="en">
      <body className={`bg-white ${inter.className}`}>
        <div>
          {isLoginPage ? (
            <>
              <Toaster position="top-center" />
              {children}
            </>
          ) : (
            <>
              <SideNav />
              <main className="flex-1">
                <MarginWidthWrapper>
                  <Header />
                  <HeaderMobile />
                  <PageWrapper>
                    <Toaster position="top-center" />
                    {children}
                  </PageWrapper>
                  <Footer />
                </MarginWidthWrapper>
              </main>
            </>
          )}
        </div>
      </body>
    </html>
  );
}